Pratique 2021 par Alexandre Tabot du livre Le Marchine Learning avec Python


note equivalance clavier mac windows sur cet ordinateur mac romain is ds

= : touche tiret
crochet ouvert : touche Alt Maj 5
crochet ferme : touche Alt Maj point d'interrogation
\ : touche Alt Maj /
\ : touche Alt Maj :
diese touche Maj touche o souligne

Marque Page
Date 04/01/2021
Chapitre 01
Page 009


In [8]:
#importation des librairie
import numpy as np

from scipy import sparse

In [9]:
#Page 9
x = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print ("x:\n{}", format(x))

eye = np.eye(4)
print("Numpy array :\n{}", format(eye))


x:
{} [[1 2 3]
 [4 5 6]]
Numpy array :
{} [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Pzge 10
sparse_matrix = sparse.csr_matrix(eye)
print("\n SciPy sparse CSR matrix :\n{}", format(sparse_matrix))


 SciPy sparse CSR matrix :
{}   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


fin prog